### ISSUE TITLE
parkour.pem no such file or directory

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/docker-parkour#4]
I generated parkour.pem using openssl and copied to nginx. Still the installation failed

Step 4/4 : ADD parkour.pem /etc/parkour.pem
ERROR: Service 'parkour-nginx' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder419664648/parkour.pem: no such file or directory

**Comment by dpryan79** [comment]
Where did you put the file?

**Comment by dpryan79** [comment]
I fixed the documentation and also mentioned that the keys need to be concatenated.
