### ISSUE TITLE
how to get my server's SSL certificate

### ISSUE THREAD

**Issue by GHKosovo** [maxplanck-ie/docker-parkour#8]
I could't find anything about the SSL certificate of  parkour in the path of /etc/ssl/certs.
No file or directory about parkour. How I could get this SSL certificate?

**Comment by dpryan79** [comment]
Normally you'd talk to your IT department and ask them to generate one for you, since they would have to sign it.

**Comment by GHKosovo** [comment]
> Normally you'd talk to your IT department and ask them to generate one for you, since they would have to sign it.

Thank you very much for your answer!
